export { default as Header } from "./common/Header";
export { default as AboutMe } from "./resume/information/AboutMe";
export { default as Information } from "./resume/information/Information";
export { default as Connection } from "./resume/information/Connection";
export { default as Skills } from "./resume/information/Skills";
export { default as Records } from "./resume/records/Records";
export { default as ProjectList } from "./resume/records/ProjectList";
export { default as Education } from "./resume/records/Education";
export { default as Achievements } from "./resume/records/Achievements";
